### ISSUE TITLE
Support For Guzzle 7

### ISSUE THREAD

**Issue by wilecoyte78** [chrisnharvey/flysystem-openstack-swift#24]
https://github.com/php-opencloud/openstack

Has been updated to 3.2. Can this package require 3.2.

**Comment by Th3Mouk** [comment]
Hi ! 
https://github.com/chrisnharvey/flysystem-openstack-swift/blob/master/composer.json#L21 already allows you to use the 3.2 version of openstack lib, no need to bump the dependency.
