### ISSUE TITLE
Create tag for main branch

### ISSUE THREAD

**Issue by alamirault** [chrisnharvey/flysystem-openstack-swift#34]
Hi,

Thanks for your package.

Hotfix https://github.com/chrisnharvey/flysystem-openstack-swift/commit/074827287f088fdcb6772da420052f98b934ffd7 was merge on master branch but no git tag was created.

Is it possible to release this patch tag ?

**Comment by mzur** [comment]
Thanks for the reminder. I've just created the [1.3.2](https://github.com/chrisnharvey/flysystem-openstack-swift/releases/tag/1.3.2) release.
